//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionDuration
    {
        public int FunctionDurationId { get; set; }
        public string FunctionName { get; set; }
        public System.DateTime StartTime { get; set; }
        public long DurationInMs { get; set; }
    }
}
